apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment-devops
  namespace: haproxy-controller-devops
  labels:
    app:  ingress-default-backend
spec:
  selector:
    matchLabels:
      app: ingress-default-backend
  replicas: 1
  template:
    metadata:
      labels:
        app:  ingress-default-backend
    spec:
      # initContainers:
        # Init containers are exactly like regular containers, except:
          # - Init containers always run to completion.
          # - Each init container must complete successfully before the next one starts.
      containers:
      - name: backend-container-devops
        image:  gcr.io/google_containers/defaultbackend:1.0
        ports:
        - containerPort: 8080
          name: backend
