apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: haproxy-cluster-role-devops
  labels:
    # Add these permissions to the "admin" and "edit" default roles.
    rbac.authorization.k8s.io/aggregate-to-admin: "true"
    rbac.authorization.k8s.io/aggregate-to-edit: "true"
rules:
- apiGroups: ["stable.example.com"]
  resources: ["Configmaps",”secrets”,"endpoints","nodes","pods","services","namespaces","events","serviceaccounts"]
  verbs: ["get", "list", "watch", "create", "update", "patch"]
