apiVersion: v1
kind: Service
metadata:
  name: ingress-service-devops
  namespace: haproxy-controller-devops
  labels:
    app: haproxy-ingress
spec:
  selector:
    app: haproxy-ingress
    type: NodePort
    tier: frontend
  ports:
  - name:  http
    protocol: "TCP"
    port: 80
    targetPort: 80
    nodePort: 32456
  - name:  https
    protocol: "TCP"
    port: 443
    targetPort: 443
    nodePort: 32567
  - name:  stat
    protocol: "TCP"
    port: 1024
    targetPort: 1024
    nodePort: 32678
  type: LoadBalancer
