apiVersion: v1
kind: Service
metadata:
  name: haproxy-service-account-devops
  namespace: haproxy-controller-devops
spec:
  selector:
    app: haproxy-service-account-devops
  type: ClusterIP
  sessionAffinity: None
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
  ports:
  - name: haproxy-service-account-devops
    protocol: TCP
    port: 8080
